### ISSUE TITLE
Error while running NSForest on a Scanpy object

### ISSUE THREAD

**Issue by siavashmoghadami** [JCVenterInstitute/NSForest#10]
Hi, I have run NSForest V3.0 using "NS_Forest(adata, clusterLabelcolumnHeader = "leiden"" command in Jupyter Notebook (on a Windows 10 OS) and the program ran for a while. However, after a few minutes I got this message: 

File <unknown>:1
    6330403 K07Rik >=1.4837858080863953
            ^
SyntaxError: invalid syntax

Would you please help me solve this issue?

**Comment by siavashmoghadami** [comment]
As an update, I realized that NSForest has an issue with gene names starting with numbers such as "6330403K07Rik" or "3110035E14Rik".

**Comment by yunzhang813** [comment]
Thanks of the ticket. Code refactored in v4.0.
