### ISSUE TITLE
Shape of passed values is (3474, 1), indices imply (3474, 33514)

### ISSUE THREAD

**Issue by ronghui1992** [JCVenterInstitute/NSForest#11]
Dear author,

I test the latest version and get this error. Is that because the number of genes exceed the limitation?
`adata = sc.read_h5ad("***.h5ad")`
`adata.obs['anno2'] = adata.obs['anno2'].astype('category')`
`adata_markers = NS_Forest(adata, clusterLabelcolumnHeader = "anno2")`

**Comment by yunzhang813** [comment]
Thanks of the ticket. Code refactored in v4.0.
