### ISSUE TITLE
Potential significant optimization with combinations instead of permutations

### ISSUE THREAD

**Issue by cdarby** [JCVenterInstitute/NSForest#3]
Based on my understanding of your algorithm and looking at the "results" and "topResults" csv output files (which contain lines with the same f-measure value for different orderings of a given set of features) I think that at this line
```
els = [list(x) for x in itertools.permutations(binarylist2, i)]
```
in the `permutor` function, you could use the `itertools.combinations` function and still explore all sets of features required. This would provide significant speedup as there are far fewer combinations than permutations.

**Comment by BAevermann** [comment]
Thank you for the suggestion. There is considerable debate over whether combinations vs permutations are needed. The permutations take considerably longer, and in my experience do not add much value (as the different permutations seem to always give the same f-beta score). This is probably a deeper issue that will need to be addressed in future development. In NSForest v3, just released, I opted for combinations as this version is meant for scanpy workflows which are time sensitive.

Thanks again, and I apologize for the delay in response!

Brian.
