### ISSUE TITLE
Index error after removal of median expressed genes

### ISSUE THREAD

**Issue by chenthorn** [JCVenterInstitute/NSForest#6]
Hello - I've been attempting to use NSForest_v3 to identify marker genes and am running into an index issue. I followed the solutions in the other two posted issues to make the cluster column categorical and to rename my clusters "cluster#", and it looks like it starts running and then throws an error after removing median expressed genes? I pasted the error I'm getting below. 

I'm pretty new to python so I apologize if there is a stupid solution. 
Thanks!

`29
cluster0
WBGene00225572
-0.6523373432931012
Is Right Out!
WBGene00225831
-0.6799969505834687
Is Right Out!
WBGene00224439
-0.06210756783551211
Is Right Out!
WBGene00234289
-0.5902925386789144
Is Right Out!
WBGene00223872
-0.7513306632741568
Is Right Out!
WBGene00233914
-0.7859160344353842
Is Right Out!
WBGene00226831
-0.7513606872951731
Is Right Out!
WBGene00234310
-0.7350392591890457
Is Right Out!
WBGene00222026
-0.7625119590800509
Is Right Out!
WBGene00226306
-0.4988349088717183
Is Right Out!
WBGene00230840
-0.043113547535310874
Is Right Out!
WBGene00234320
-0.45560893452216766
Is Right Out!
WBGene00224751
-0.7094634997854268
Is Right Out!
WBGene00222262
-0.41389846421983106
Is Right Out!
WBGene00222044
-0.7698303495034613
Is Right Out!
[]
0
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/var/folders/xl/ly4bqc356sd34lm07_ggzdw1pfgrjf/T/ipykernel_22678/4072770710.py in <module>
      1 # run NSForest on BM_combined
----> 2 adata_markers = NS_Forest(adata, clusterLabelcolumnHeader = 'integrated_snn_res.0.5')

/var/folders/xl/ly4bqc356sd34lm07_ggzdw1pfgrjf/T/ipykernel_22678/3411186380.py in NS_Forest(adata, clusterLabelcolumnHeader, rfTrees, Median_Expression_Level, Genes_to_testing, betaValue)
    217         FullpermutationList = permutor(queryInequalities)
    218         print(len(FullpermutationList))
--> 219         f1_store = fbetaTest(FullpermutationList, column, adata, Binary_RankedList, testArray, betaValue)
    220         f1_store_1D.update(f1_store)
    221 

/var/folders/xl/ly4bqc356sd34lm07_ggzdw1pfgrjf/T/ipykernel_22678/3411186380.py in fbetaTest(x, column, adata, Binary_RankedList, testArray, betaValue)
    120         fbeta_dict = {}
    121         subset_adata = adata[:,Binary_RankedList]
--> 122         Subset_dataframe = pd.DataFrame(data = subset_adata.X, index = subset_adata.obs_names, columns = subset_adata.var_names)
    123         Subset_dataframe.columns = Subset_dataframe.columns.str.replace("-", "_").str.replace(".", "_")
    124 

~/miniconda3/lib/python3.9/site-packages/anndata/_core/anndata.py in X(self)
    623         elif self.is_view:
    624             X = as_view(
--> 625                 _subset(self._adata_ref.X, (self._oidx, self._vidx)),
    626                 ElementRef(self, "X"),
    627             )

~/miniconda3/lib/python3.9/functools.py in wrapper(*args, **kw)
    875                             '1 positional argument')
    876 
--> 877         return dispatch(args[0].__class__)(*args, **kw)
    878 
    879     funcname = getattr(func, '__name__', 'singledispatch function')

~/miniconda3/lib/python3.9/site-packages/anndata/_core/index.py in _subset(a, subset_idx)
    125     if all(isinstance(x, cabc.Iterable) for x in subset_idx):
    126         subset_idx = np.ix_(*subset_idx)
--> 127     return a[subset_idx]
    128 
    129 

IndexError: arrays used as indices must be of integer (or boolean) type`

**Comment by yunzhang813** [comment]
Thanks of the ticket. Code refactored in v4.0.
