### ISSUE TITLE
Use features identified by NS Forest in Seurat

### ISSUE THREAD

**Issue by SHADJIA** [JCVenterInstitute/NSForest#8]
Hello,

I tried your code to delineate the minimum marker genes to characterize subsets of Treg cells. Generally, I work with Seurat package to analyse my singlecell projects. I would like to generate a UMAP plot by using genes identified with NS Forest (2.0 and 1.3). For that, I did a subset of the initial SeuratObject by specifiying the identified genes as features. Then, I performed "FindNeighbors", "FindClusters" and "RunUMAP". Typically, I find the same plot between the one with 2000 genes and the one with 50 genes. 
Have you ever tried to combine Seurat and your tool, rather than Scanpy? 

Thank you in advance

**Comment by yunzhang813** [comment]
Thanks of the ticket. Code refactored in v4.0.
